# Generated by Django 3.1 on 2020-08-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='lable',
            new_name='label',
        ),
    ]
